[package]
name = "aptos-indexer-grpc-stream-server"
description = "Aptos gRPC stream server"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
hyper = { workspace = true}
tonic-reflection = { workspace = true }
tonic = { workspace = true }